= Storing passwords

== Concept

This lesson teaches about how to store password within your application and what the best practices are.

== Goals

Learn about all the methods storing passwords went through and learn about the best practices for storing passwords safely in your system.

== Introduction

We read about password breaches a lot in the news, users often use the same passwords across multiple websites and a breach from your company might impact users across different sites. With the advent of GDPR companies are now liable for such a breach, and the financial consequences can be quite high.

In this lesson we will go through the several phases storing a password went through. In the end, we will show the current best practice to use in your application.

Still, some companies will send the password in plaintext to a user in an e-mail. For a couple of examples,
you can take a look at http://plaintextoffenders.com/. Here you will find websites that still send you the plaintext
password in an e-mail. Not only this should make you question the security of the site but this also means they store
your password in plain text!

