= Encryption of the passwords

One way to solve the storing of plaintext passwords is to encrypt each password before storing it into the database. Let's see why this is not a good idea as well.

Suppose before we store each password we encrypt the password with a fixed key, when the user tries to log in we decrypt the password and compare the two.

|===
|username | name | password

|jdoe| John Doe | NSqKWB5CXZzMFIvcBsCs1Q==
|alice | Alice | lOFyZeKAH62IO37GlUQ7Rg==
|steve01 | Steve | r1cOHG7rf/3YQuFNtl7Lzg==
|===

As we can see when the database leaks due to, for example, an SQL injection it does not immediately give the attacker the ability to learn the passwords. The attacker can, however, "guess" some frequently used passwords as the encryption of the same password will have the same ciphertext. For example, suppose a new user also uses `qwerty` as password the result will be:

|===
|username | name | password

|jdoe| John Doe | NSqKWB5CXZzMFIvcBsCs1Q==
|alice | Alice | lOFyZeKAH62IO37GlUQ7Rg==
|steve01 | Steve | r1cOHG7rf/3YQuFNtl7Lzg==
|cindy | Cindy | r1cOHG7rf/3YQuFNtl7Lzg==
|===

As we can see Steve and Cindy share the same password as we can see in the table. Users on the other hand often use the same well-known password so if one can create a frequency table based on the encrypted ciphertext it is possible after a couple of attempts to guess the password. https://www.theguardian.com/technology/2013/nov/07/adobe-password-leak-can-check[Adobe] was prone to this error, they used the same key for each user, and they used an insecure method of encrypting the data which caused the same encrypted password to be the same.

In practice using encryption for storing passwords is not the best option there are better options to use, let's continue to the next section.



